var quiz = [
  [1, 1, "Tempat wisata favorit di Bandung", "LEMBANG", "datar"],
  [1, 3, "Mie khas Bandung yang menggunakan toping kikil", "MIEKOCOK", "turun"],
  [
    1,
    5,
    "Daerah di Bandung yang terkenal dengan lukisan muralnya",
    "ANTAPANI",
    "turun",
  ],
  [5, 7, "Tempat jual beli elektronik populer di Bandung", "BEC", "datar"],
  [6, 5, "Tempat rekreasi keluarga di Bandung timur", "ALUNALUNUBER", "datar"],
  [1, 7, "Tempat jogging paling terkenal di Bandung", "GASIBU", "turun"],
  [5, 9, "Pusat grosir sayur di Bandung", "CARINGIN", "turun"],
  [10, 9, "Markas Persib Bandung", "GBLA", "datar"],
  [
    12,
    7,
    "Campuran sayuran dan kelapa parut dengan bumbu khas Sunda",
    "URAB",
    "turun",
  ],
  [
    12,
    6,
    "Hidangan berkuah yang cocok dinikmati saat cuaca dingin",
    "CUANKI",
    "datar",
  ],
];
